assignment_name: assignment name
subtitle: assignment subtitle
version: 0.0.1
topics: this, that, and the other
points_cap: points cap
total_points: total points
global_imports:
- module: re
- module: pandas
  alias: pd
exercises: {}
